version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/apps/frontend"
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/apps/backend"
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/apps/backend/lambdas/match-api"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/apps/backend/lambdas/score-update"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/apps/backend/lambdas/storage-worker"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/apps/e2e"
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        patterns:
          - "*"

  - package-ecosystem: "terraform"
    directory: "/infra/terraform"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        patterns:
          - "*"
