environment      = "dev"
project_name     = "cricscoredev"
domain_name      = "cricscoredev.venkateshsingamsetty.site"
zone_domain      = "venkateshsingamsetty.site"
subdomain_prefix = "cricscoredev"
