skip-check:
  - CKV2_AWS_16
  - CKV2_AWS_23
  - CKV2_AWS_32
  - CKV2_AWS_40
  - CKV2_AWS_42
  - CKV2_AWS_46
  - CKV2_AWS_47
  - CKV2_AWS_51
  - CKV2_AWS_54
  - CKV2_AWS_56
  - CKV2_AWS_6
  - CKV2_AWS_61
  - CKV2_AWS_62
  - CKV2_AWS_64
  - CKV2_AWS_71
  - CKV2_AWS_72
  - CKV2_AWS_75
  - CKV2_AWS_77
  - CKV_AWS_1
  - CKV_AWS_107
  - CKV_AWS_108
  - CKV_AWS_109
  - CKV_AWS_110
  - CKV_AWS_111
  - CKV_AWS_115
  - CKV_AWS_116
  - CKV_AWS_117
  - CKV_AWS_119
  - CKV_AWS_144
  - CKV_AWS_145
  - CKV_AWS_158
  - CKV_AWS_168
  - CKV_AWS_173
  - CKV_AWS_174
  - CKV_AWS_18
  - CKV_AWS_19
  - CKV_AWS_20
  - CKV_AWS_21
  - CKV_AWS_216
  - CKV_AWS_227
  - CKV_AWS_233
  - CKV_AWS_234
  - CKV_AWS_259
  - CKV_AWS_26
  - CKV_AWS_27
  - CKV_AWS_272
  - CKV_AWS_274
  - CKV_AWS_28
  - CKV_AWS_283
  - CKV_AWS_286
  - CKV_AWS_287
  - CKV_AWS_288
  - CKV_AWS_289
  - CKV_AWS_290
  - CKV_AWS_301
  - CKV_AWS_305
  - CKV_AWS_309
  - CKV_AWS_310
  - CKV_AWS_33
  - CKV_AWS_338
  - CKV_AWS_34
  - CKV_AWS_355
  - CKV_AWS_356
  - CKV_AWS_358
  - CKV_AWS_363
  - CKV_AWS_364
  - CKV_AWS_374
  - CKV_AWS_387
  - CKV_AWS_393
  - CKV_AWS_41
  - CKV_AWS_45
  - CKV_AWS_49
  - CKV_AWS_50
  - CKV_AWS_53
  - CKV_AWS_54
  - CKV_AWS_55
  - CKV_AWS_56
  - CKV_AWS_57
  - CKV_AWS_60
  - CKV_AWS_61
  - CKV_AWS_62
  - CKV_AWS_63
  - CKV_AWS_66
  - CKV_AWS_68
  - CKV_AWS_7
  - CKV_AWS_72
  - CKV_AWS_76
  - CKV_AWS_86
  - CKV_AWS_93
