name: DAST (OWASP ZAP)

on:
  workflow_run:
    workflows: ["Frontend CI/CD"]
    types:
      - completed
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
  workflow_dispatch:

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  zap_scan:
    name: ZAP Baseline Scan
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Fix workspace permissions for ZAP Docker
        run: chmod -R 777 ${{ github.workspace }}

      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.15.0
        with:
          target: 'https://cricscore.venkateshsingamsetty.site'
          fail_action: false # We only want reporting for DAST right now, not to block pipelines outright
